export const PRODUCTOS_ARGENTINOS = [
  // Carnicería (Venta por peso)
  { nombre: "Asado", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Vacío", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Entraña", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { carne: true, nombre: "Matambre", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Chorizo Puro Cerdo", categoria: "carniceria", esPeso: true, icon: "sausage" },
  { nombre: "Morcilla", categoria: "carniceria", esPeso: true, icon: "sausage" },
  { nombre: "Tapa de Asado", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Falda", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Roast Beef", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Nalga", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Cuadril", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Bola de Lomo", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Peceto", categoria: "carniceria", esPeso: true, icon: "food-steak" },
  { nombre: "Milanesa de Pollo", categoria: "carniceria", esPeso: true, icon: "food-drumstick" },
  { nombre: "Pollo Entero", categoria: "carniceria", esPeso: true, icon: "food-turkey" },
  { nombre: "Pechuga de Pollo", categoria: "carniceria", esPeso: true, icon: "food-drumstick" },
  { nombre: "Pata Muslo", categoria: "carniceria", esPeso: true, icon: "food-drumstick" },

  // Verdulería (Venta por peso o unidad)
  { nombre: "Papa Negra", categoria: "verduleria", esPeso: true, icon: "potato" },
  { nombre: "Papa Blanca", categoria: "verduleria", esPeso: true, icon: "potato" },
  { nombre: "Cebolla", categoria: "verduleria", esPeso: true, icon: "onion" },
  { nombre: "Cebolla Morada", categoria: "verduleria", esPeso: true, icon: "onion" },
  { nombre: "Tomate Redondo", categoria: "verduleria", esPeso: true, icon: "fruit-cherries" }, // tomato not standard in all MDI versions, fallback
  { nombre: "Tomate Perita", categoria: "verduleria", esPeso: true, icon: "fruit-cherries" },
  { nombre: "Zanahoria", categoria: "verduleria", esPeso: true, icon: "carrot" },
  { nombre: "Lechuga Capuchina", categoria: "verduleria", esPeso: false, icon: "leaf" },
  { nombre: "Lechuga Mantecosa", categoria: "verduleria", esPeso: false, icon: "leaf" },
  { nombre: "Morrón Rojo", categoria: "verduleria", esPeso: true, icon: "pepper" },
  { nombre: "Morrón Verde", categoria: "verduleria", esPeso: true, icon: "pepper" },
  { nombre: "Zapallo Anco", categoria: "verduleria", esPeso: true, icon: "food-apple" },
  { nombre: "Zapallito", categoria: "verduleria", esPeso: true, icon: "food-apple" },
  { nombre: "Acelga", categoria: "verduleria", esPeso: false, icon: "leaf" },
  { nombre: "Espinaca", categoria: "verduleria", esPeso: false, icon: "leaf" },
  { nombre: "Banana", categoria: "verduleria", esPeso: true, icon: "fruit-watermelon" }, // fallback
  { nombre: "Manzana Roja", categoria: "verduleria", esPeso: true, icon: "food-apple" },
  { nombre: "Manzana Verde", categoria: "verduleria", esPeso: true, icon: "food-apple" },
  { nombre: "Naranja Jugo", categoria: "verduleria", esPeso: true, icon: "fruit-citrus" },
  { nombre: "Naranja Ombligo", categoria: "verduleria", esPeso: true, icon: "fruit-citrus" },
  { nombre: "Mandarina", categoria: "verduleria", esPeso: true, icon: "fruit-citrus" },
  { nombre: "Limón", categoria: "verduleria", esPeso: true, icon: "fruit-citrus" },
  { nombre: "Pera", categoria: "verduleria", esPeso: true, icon: "fruit-pear" },
  { nombre: "Uva", categoria: "verduleria", esPeso: true, icon: "fruit-grapes" },
  { nombre: "Durazno", categoria: "verduleria", esPeso: true, icon: "food-apple" },

  // Sueltos y Fiambrería
  { nombre: "Huevos Colorados (Maple)", categoria: "sueltos", esPeso: false, icon: "egg" },
  { nombre: "Huevos Blancos (Maple)", categoria: "sueltos", esPeso: false, icon: "egg" },
  { nombre: "Pan Francés", categoria: "almacen", esPeso: true, icon: "baguette" },
  { nombre: "Pan rallado", categoria: "almacen", esPeso: true, icon: "bowl-mix" },
  { nombre: "Queso Máquina", categoria: "sueltos", esPeso: true, icon: "cheese" },
  { nombre: "Queso Cremoso", categoria: "sueltos", esPeso: true, icon: "cheese" },
  { nombre: "Jamón Cocido", categoria: "sueltos", esPeso: true, icon: "food-variant" },
  { nombre: "Paleta", categoria: "sueltos", esPeso: true, icon: "food-variant" },
  { nombre: "Salame", categoria: "sueltos", esPeso: true, icon: "sausage" },

  // Almacén
  { nombre: "Yerba Mate (500g)", categoria: "almacen", esPeso: false, icon: "leaf" },
  { nombre: "Yerba Mate (1kg)", categoria: "almacen", esPeso: false, icon: "leaf" },
  { nombre: "Azúcar (1kg)", categoria: "almacen", esPeso: false, icon: "spoon-sugar" },
  { nombre: "Harina 0000 (1kg)", categoria: "almacen", esPeso: false, icon: "sack" },
  { nombre: "Harina 000 (1kg)", categoria: "almacen", esPeso: false, icon: "sack" },
  { nombre: "Arroz (1kg)", categoria: "almacen", esPeso: false, icon: "rice" },
  { nombre: "Fideos Tallarines (500g)", categoria: "almacen", esPeso: false, icon: "noodles" },
  { nombre: "Fideos Mostacholes (500g)", categoria: "almacen", esPeso: false, icon: "noodles" },
  { nombre: "Aceite de Girasol (900ml)", categoria: "almacen", esPeso: false, icon: "bottle-tonic" },
  { nombre: "Aceite de Girasol (1.5L)", categoria: "almacen", esPeso: false, icon: "bottle-tonic" },
  { nombre: "Puré de Tomate (520g)", categoria: "almacen", esPeso: false, icon: "food-apple" },
  { nombre: "Leche Larga Vida (1L)", categoria: "almacen", esPeso: false, icon: "cup-water" },
];